apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc-dynamic
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-vm-csi
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-svc
  labels:
    run: mongo-svc
spec:
  type: LoadBalancer
  ports:
  - port: 27017
    targetPort: 27017 
    protocol: TCP
    name: mongo
  selector:
    app: mongo-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-test
spec:
  selector:
    matchLabels:
      app: mongo-test
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo-test
    spec:
      containers:
      - name: mongodb
        image: docker.io/mongo
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
        ports:
        - containerPort: 27017
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
           claimName: mongo-pvc-dynamic
